version: 2
dependencies:
  pre:
    - npm install npm@latest -g
    - npm install angular-cli@latest -g
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: npm-install-concur
      - run: npm install
deployment:
  production:
    branch: master
    codedeploy:
      MimiAngular2:
        deployment_group: MimiAngular2
