version: 2
dependencies:
  pre:
    - npm install npm@latest -g
    - npm install -g @angular/cli
jobs:
  build:
    docker:
      - image: circleci/node:10.5.0-stretch-browsers
    steps:
      - checkout
      - run: npm install
      - run: node node_modules/@angular/cli/bin/ng build --prod
deployment:
  production:
    branch: master
    codedeploy:
      MimiAngular2:
        deployment_group: MimiAngular2
