version: 2
dependencies:
  pre:
    - npm install npm@latest -g
    - npm install @angular/cli@latest -g
    - npm i -g rxjs
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: npm install
deployment:
  production:
    branch: master
    codedeploy:
      MimiAngular2:
        deployment_group: MimiAngular2
