version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - checkout
      - run:
          name: yarn-install-ng
          command: 'sudo yarn global add @angular-cli'
      - run:
          name: npm-install-concur
          command: 'sudo yarn global add concurrently'
      - run: yarn install
